name=input("Enter Name ")
print(name.upper())
print(name.lower())
print(name.title())
print(name.islower())
print(name.isupper())
print(name.isalnum())
print(name.isalpha()) 
print(name.istitle())
print(name.isspace())